[package]
name = "lssbi"
version = "0.0.0"
edition = "2024"
build = "build.rs"
description = "List information about the active RISC-V SBI environment."
authors = ["Zhouqi Jiang <luojia@rustsbi.com>"]
license = "MIT OR MulanPSL-2.0"
readme = "README.md"
keywords = ["riscv", "sbi", "linux"]
categories = ["command-line-utilities", "hardware-support"]

[dependencies]
clap = { version = "4.5", default-features = false, features = ["derive", "help", "std", "usage"] }
gettext-rs = { version = "0.8", features = ["gettext-system"] }
jep106 = { version = "0.3", default-features = false }
libc = "0.2"
nix = { version = "0.31.3", features = ["signal", "user"] }
pam-sys = { package = "pam-sys2", version = "1.0.2" }
sbi-spec = { version = "0.0.9", features = ["legacy"] }
unicode-width = "0.2"

[build-dependencies]
polib = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
