# SPDX-License-Identifier: MIT OR MulanPSL-2.0

PACKAGE_NAME="lssbi"
PACKAGE_VERSION="0.0.1"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_ARCH="riscv64"
BUILD_EXCLUSIVE_CONFIG="CONFIG_RISCV_SBI"

MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/kernel modules"
BUILT_MODULE_NAME[0]="lssbi_probe"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"
